#!/bin/bash
#
# chkconfig: 2345 85 15
# description: Starts and stops the PostgreSQL 9.3 database server

# Source function library.
if [ -f /etc/rc.d/functions ];
then
    . /etc/init.d/functions
fi

# PostgreSQL Service script for Linux

start()
{
	echo $"Starting PostgreSQL 9.3: "
	su -s /bin/sh - postgres -c "LD_LIBRARY_PATH=/opt/PostgreSQL/9.3/lib:$LD_LIBRARY_PATH /opt/PostgreSQL/9.3/bin/pg_ctl -w start -D \"/opt/PostgreSQL/9.3/data\" -l \"/opt/PostgreSQL/9.3/data/pg_log/startup.log\""
	
	if [ $? -eq 0 ];
	then
		echo "PostgreSQL 9.3 started successfully"
                exit 0
	else
		echo "PostgreSQL 9.3 did not start in a timely fashion, please see /opt/PostgreSQL/9.3/data/pg_log/startup.log for details"
                exit 1
	fi
}

stop()
{
	echo $"Stopping PostgreSQL 9.3: "
	su -s /bin/sh - postgres -c "LD_LIBRARY_PATH=/opt/PostgreSQL/9.3/lib:$LD_LIBRARY_PATH /opt/PostgreSQL/9.3/bin/pg_ctl stop -m fast -w -D \"/opt/PostgreSQL/9.3/data\""
}

restart()
{
	echo $"Restarting PostgreSQL 9.3: "
	su -s /bin/sh - postgres -c "LD_LIBRARY_PATH=/opt/PostgreSQL/9.3/lib:$LD_LIBRARY_PATH /opt/PostgreSQL/9.3/bin/pg_ctl -w restart -D \"/opt/PostgreSQL/9.3/data\" -l \"/opt/PostgreSQL/9.3/data/pg_log/startup.log\" -m fast"
	
	if [ $? -eq 0 ];
	then
		echo "PostgreSQL 9.3 restarted successfully"
                exit 0
	else
		echo "PostgreSQL 9.3 did not start in a timely fashion, please see /opt/PostgreSQL/9.3/data/pg_log/startup.log for details"
                exit 1
	fi
}

reload()
{
	echo $"Reloading PostgreSQL 9.3: "
	su -s /bin/sh - postgres -c "LD_LIBRARY_PATH=/opt/PostgreSQL/9.3/lib:$LD_LIBRARY_PATH /opt/PostgreSQL/9.3/bin/pg_ctl reload -D \"/opt/PostgreSQL/9.3/data\""
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  reload)
	reload
	;;
  condrestart)
        if [ -f "/opt/PostgreSQL/9.3/data/postmaster.pid" ]; then
            restart
        fi
        ;;
  status)
        su -s /bin/sh - postgres -c "LD_LIBRARY_PATH=/opt/PostgreSQL/9.3/lib:$LD_LIBRARY_PATH /opt/PostgreSQL/9.3/bin/pg_ctl status -D \"/opt/PostgreSQL/9.3/data\""
        ;;
  *)
        echo $"Usage: /opt/PostgreSQL/9.3/installer/server/startupcfg.sh {start|stop|restart|condrestart|status}"
        exit 1
esac

